### ISSUE TITLE
Message not sent by Wear or message not received by phone

### ISSUE THREAD

**Issue by ericvangeem** [tgardner/cordova-androidwear-example#1]
Following all the instructions in the README, I was able to successfully send messages to the watch from the cordova app, however sending messages to the cordova app from the watch does not seem to work. 

**Expected results**: "Hello from AndroidWear" should appear on the Cordova app's screen when pressing the SEND MESSAGE button on the wear app.

**Actual results**: Nothing changes on the Cordova app's screen when pressing the SEND MESSAGE button on the wear app.

**Comment by tgardner** [comment]
Hi @archee,

Are you testing using the android wear emulator or a device?
I've added a Makefile to the example project to bundle the wearable apk for you incase you've missed something. Can you please have your phone plugged in and try the following

``` shell
git pull
make
make install
```

I've tested this with the android wear emulator and it seems to function as expected.

Thanks,

Trent

**Comment by ericvangeem** [comment]
Hi Trent,

I have been testing this with my Moto 360 device. If I have time today I will try again with an emulator (in addition to using your make file) and report back here with the results.

Thanks,

Eric
